import pygame

FLOOR = 0
BRICK = 1

tilemap = [
    [BRICK, BRICK, BRICK, BRICK, BRICK, BRICK, BRICK, BRICK, BRICK, BRICK, BRICK, BRICK, BRICK, BRICK, BRICK],
    [BRICK, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, BRICK],
    [BRICK, FLOOR, BRICK, FLOOR, BRICK, FLOOR, BRICK, FLOOR, BRICK, FLOOR, BRICK, FLOOR, BRICK, FLOOR, BRICK],
    [BRICK, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, BRICK],
    [BRICK, FLOOR, BRICK, FLOOR, BRICK, FLOOR, BRICK, FLOOR, BRICK, FLOOR, BRICK, FLOOR, BRICK, FLOOR, BRICK],
    [BRICK, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, BRICK],
    [BRICK, FLOOR, BRICK, FLOOR, BRICK, FLOOR, BRICK, FLOOR, BRICK, FLOOR, BRICK, FLOOR, BRICK, FLOOR, BRICK],
    [BRICK, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, BRICK],
    [BRICK, FLOOR, BRICK, FLOOR, BRICK, FLOOR, BRICK, FLOOR, BRICK, FLOOR, BRICK, FLOOR, BRICK, FLOOR, BRICK],
    [BRICK, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, BRICK],
    [BRICK, FLOOR, BRICK, FLOOR, BRICK, FLOOR, BRICK, FLOOR, BRICK, FLOOR, BRICK, FLOOR, BRICK, FLOOR, BRICK],
    [BRICK, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, BRICK],
    [BRICK, BRICK, BRICK, BRICK, BRICK, BRICK, BRICK, BRICK, BRICK, BRICK, BRICK, BRICK, BRICK, BRICK, BRICK]
]